title: Linda Writes
author: GitHub User
email: lindaedwin96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Articles on Web Development, written by Linda Ikechukwu, Web Developer based in Port Harcourt, Nigeria.

# social links
twitter_username: https://twitter.com/Bad__Geek
github_username:  https://github.com/Linda-Ikechukwu

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
